forge "http://forge.puppetlabs.com"

mod 'puppetlabs-apt', '2.3.0'
mod 'puppetlabs-puppet_agent', '1.3.2'
mod 'puppetlabs-java', '1.6.0'
mod 'adrien-alternatives', '0.3.0'
mod 'puppetlabs-stdlib', '4.15.0'

