Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/trusty64"
    config.vm.hostname = "mesos-master"
    config.vm.define "mesos-master"
    config.vm.network "forwarded_port", guest: 8080, host: 9000
    config.vm.network "forwarded_port", guest: 5050, host: 9001

    config.vm.provider"virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end

    config.librarian_puppet.puppetfile_dir = './puppetforge'
    config.librarian_puppet.placeholder_filename = ".MYPLACEHOLDER"
    config.librarian_puppet.use_v1_api = '1'
    config.librarian_puppet.destructive = false


    config.vm.synced_folder "./hiera", "/etc/hiera" 
    config.vm.provision "puppet" do |puppet|
        puppet.manifests_path = "./manifests"
        puppet.manifest_file = "init.pp"
        puppet.module_path = [ "./modules", "./puppetforge/modules"]
        puppet.hiera_config_path = "./hiera/vagrant_hiera.yaml"
        puppet.options = "--verbose --debug"
        puppet.facter = {
            "fqdn" => "mesos-master"
        }
    end
end
