unless Vagrant.has_plugin?("vagrant-berkshelf")
    raise "Plugin not found. vagrant plugin install vagrant-berkshelf"
end

Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/trusty64"
    config.vm.hostname = "mesos-master"
    config.vm.define "mesos-master"
    config.vm.network "public_network"

    config.vm.provider"virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end

    config.berkshelf.berksfile_path = "./Berksfile"
    config.berkshelf.enabled = true

    config.vm.provision "chef_solo" do |chef|
        chef.cookbooks_path = './cookbooks'
        chef.roles_path = './roles'
        chef.add_role('zookeeper')
        chef.add_role('mesos_master')
        chef.add_role('mesos_agent')
        chef.add_role('marathonlb')
    end


end
